export const fieldTypes = {
  TEXT_INPUT: "text_input",
};
export const subTypes = {
  TEXT: "text",
  EMAIL: "email",
  CHECKBOX: "checkbox",
  COLOR: "color",
  DATE: "date",
  DATETIME_LOCAL: "datetime-local",
  FILE: "file",
  HIDDEN: "hidden",
  IMAGE: "image",
  MONTH: "month",
  NUMBER: "number",
  PASSWORD: "password",
  RADIO: "radio",
  RANGE: "range",
  RESET: "reset",
  SEARCH: "search",
  SUBMIT: "submit",
  TEL: "tel",
  TIME: "time",
  URL: "url",
  WEEK: "week",
};
