import { fieldTypes, subTypes } from "../Const/types";

export const productPage = {
  title: "Product Page",
  sourceLabel: "product",
  optionSetLabels: ["category", "subcategory", "sku"],
  formConfig: {
    formElements: [
      {
        formType: fieldTypes.TEXT_INPUT,
        subType: subTypes.TEXT,
        tableLabel: "Name",
        id: "productName",
        defaultValue: "",
        helperText: "",
        label: "Product Name:",
        required: true,
      },
      {
        tableLabel: "Category",
        id: "productCategoryName",
        defaultValue: "",
        helperText: "",
        label: "Category Name:",
        required: true,
        hideInForm: true,
        formType: fieldTypes.OPTION_SET,
        optionSetName: "category",
        optionSetLabel: "categoryName",
        optionSetValue: "categoryName",
        placeholder: "Please Select Category",
      },
      {
        tableLabel: "Sub Category",
        id: "subcategoryName",
        defaultValue: "",
        helperText: "",
        label: "Sub Category Name:",
        required: true,
        hideInForm: true,
        formType: fieldTypes.OPTION_SET,
        optionSetName: "subcategory",
        optionSetLabel: "subcategoryName",
        optionSetValue: "subcategoryName",
        placeholder: "Please Select Sub Category",
      },
      {
        tableLabel: "SKU",
        id: "skuLabel",
        defaultValue: "",
        helperText: "",
        label: "SKU Label:",
        required: true,
        hideInForm: true,
        formType: fieldTypes.OPTION_SET,
        optionSetName: "sku",
        optionSetLabel: "skuLabel",
        optionSetValue: "skuLabel",
        placeholder: "Please Select SKU",
      },
      {
        formType: fieldTypes.TEXT_INPUT,
        subType: subTypes.EMAIL,
        tableLabel: "MRP",
        id: "productMRP",
        defaultValue: "",
        helperText: "",
        label: "Product MRP:",
      },
      {
        formType: fieldTypes.TEXT_INPUT,
        subType: subTypes.URL,
        tableLabel: "Desc",
        id: "productDescription",
        defaultValue: "",
        helperText: "",
        label: "Description:",
      },
    ],
  },
};

export const categoryPage = {
  sourceLabel: "category",
  title: "Category Page",
  optionSetLabels: ["category", "subCategory"],
  edit: true,
  delete: true,
  formConfig: {
    edit: true,
    delete: true,
    formElements: [
      {
        formType: fieldTypes.TEXT_INPUT,
        subType: subTypes.TEXT,
        tableLabel: "Category",
        id: "categoryName",
        defaultValue: "",
        helperText: "",
        label: "Category Name:",
        required: true,
        hideInForm: true,
      },
    ],
  },
};
export const subcategoryPage = {
  sourceLabel: "subcategory",
  title: "Sub Category Page",
  optionSetLabels: ["category"],
  edit: true,
  delete: true,
  formConfig: {
    edit: true,
    delete: true,
    formElements: [
      {
        tableLabel: "Category",
        id: "categoryName",
        defaultValue: "",
        helperText: "",
        label: "Category Name:",
        required: true,
        hideInForm: true,
        formType: fieldTypes.OPTION_SET,
        optionSetName: "category",
        optionSetLabel: "categoryName",
        optionSetValue: "categoryName",
        placeholder: "Please Select Category",
      },
      {
        formType: fieldTypes.TEXT_INPUT,
        subType: subTypes.TEXT,
        tableLabel: "Sub Category",
        id: "subcategoryName",
        defaultValue: "",
        helperText: "",
        label: "Sub Category :",
        required: true,
        hideInForm: true,
      },
    ],
  },
};
export const SKUPage = {
  sourceLabel: "sku",
  title: "Sub Category Page",
  optionSetLabels: ["category"],
  edit: true,
  delete: true,
  formConfig: {
    edit: true,
    delete: true,
    formElements: [
      {
        formType: fieldTypes.TEXT_INPUT,
        subType: subTypes.TEXT,
        tableLabel: "SKU Label",
        id: "skuLabel",
        defaultValue: "",
        helperText: "",
        label: "SKU Label:",
        required: true,
        hideInForm: true,
      },
    ],
  },
};
